appname="集合"
appver="1.1"
appcode="1"
appsdk="22"
path_pattern="lua"
packagename="com.alittlemc.gather"
theme="Theme_DeviceDefault_Light_NoActionBar_TranslucentDecor"
app_key=""
app_channel=""
developer="alittlemc"
description=""
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
